fail_fast: true

default_stages: [commit, push]

default_language_version:
  python: python3.12
minimum_pre_commit_version: 2.20.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
        args: ["--maxkb=1400", "--enforce-all"]
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-byte-order-marker # forbids files which have a utf-8 byte-order marker.
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive file systems.
      - id: check-docstring-first # checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: pretty-format-json # sets a standard for formatting json files.
        args: ["--autofix"]
        exclude: package-lock.json|.ipynb
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: name-tests-test # verifies that test files are named correctly.
        args: ["--django"] # also matches *_test
      # - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: sort-simple-yaml # sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
      - id: trailing-whitespace # trims trailing whitespace.

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-check-blanket-noqa # Enforce that `noqa` annotations always occur with specific codes. Sample annotations: `# noqa: F401`, `# noqa: F401,W203`
      # - id: python-check-blanket-type-ignore # Enforce that `# type: ignore` annotations always occur with specific codes. Sample annotations: `# type: ignore[attr-defined]`, `# type: ignore[attr-defined, name-defined]`
      - id: python-check-mock-methods # Prevent common mistakes of `assert mck.not_called()`, `assert mck.called_once_with(...)` and `mck.assert_called`.
      - id: python-no-eval # A quick check for the `eval()` built-in function
      - id: python-no-log-warn # A quick check for the deprecated `.warn()` method of python loggers
      - id: python-use-type-annotations # Enforce that python3.6+ type annotations are used instead of type comments
      - id: rst-backticks # Detect common mistake of using single backticks when writing rst
      - id: rst-directive-colons # Detect mistake of rst directive not ending with double colon
      - id: rst-inline-touching-normal # Detect mistake of inline code touching normal text in rst
      - id: text-unicode-replacement-char # Forbid files which have a UTF-8 Unicode replacement character

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.1"
    hooks:
      - id: pyupgrade # Automatically upgrade syntax for newer versions.
        args: [--py311-plus]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/kynan/nbstripout
    rev: "0.7.1"
    hooks:
      - id: nbstripout
        exclude: examples\/user_classification\.ipynb
        args: ["--drop-empty-cells"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.8.4"
    hooks:
      - id: nbqa-check-ast # Run 'check-ast' on a Jupyter Notebook
      - id: nbqa-pyupgrade # Run 'pyupgrade' on a Jupyter Notebook

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.353
    hooks:
      - id: pyright

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0" # add version here
    hooks:
      - id: poetry-check
        stages: [commit-msg]
      - id: poetry-lock
        stages: [commit-msg]
      - id: poetry-export
        stages: [commit-msg]
        args:
          ["-f", "requirements.txt", "-o", "requirements.txt", "--only", "main"]
